### ISSUE TITLE
@extends('admin::layouts.master')

### ISSUE THREAD

**Issue by illuminate3** [yajra/cms-core#2]
### Summary of problem or feature request

The resource views don't see, to exist.
@extends('admin::layouts.master')

Is there a missing package or do we need to create our own?

thanks!

**Comment by yajra** [comment]
@illuminate3 thanks for the interest. There is another package/main platform that should be used for this to work. Haven't released the code yet in public though.

**Comment by illuminate3** [comment]
Thank you for the response.
I'm gonna close this since your response answered my question in way.
