### ISSUE TITLE
Dependency nwidart/modules is missing

### ISSUE THREAD

**Issue by noxify** [yajra/cms-core#3]
### Summary of problem or feature request

After installing the latest 3.* version, i got an error while running 

```
 php artisan route:list
```

### Code snippet of problem

```php
php artisan route:list
                                                   
  [ReflectionException]                            
  Class Nwidart\Modules\Repository does not exist 
```

### Workaround 

After running 

```
composer require nwidart/laravel-modules
```

I was able to run the `php artisan route:list` command.

### System details

- Operating System: OSX 10.11.6
- PHP Version: 7.1.15
- Laravel Version: 5.4.25
- Package Version: cms-core -> 3.10.2

**Comment by yajra** [comment]
Oh thanks! Added the required packages on v3.10.3.

Just curious, were you able to use this package? I haven't totally open source the `cms-platform` I am using for this to work. Still working on it but will release it soon (Still thinking of the license though ^_^). Thanks!

**Comment by noxify** [comment]
I got then some other errors :)

* auth.login view is missing inside the Package 
* if i try to open `localhost/administrator` i got an error that the class administrator is missing/can't be found

But i will test it with your mentioned package if it's available :)

It was more a Test from my side to See what you're doing here ;)

**Comment by yajra** [comment]
@noxify thanks for the interest. You can actually review the functionality using this site.

http://demo.yajracms.com/
http://demo.yajracms.com/administrator
```
Account: admin@example.com / secret
```

**Comment by noxify** [comment]
I close this issue, because the problem is solved with the referenced commit
